name: BloodMoonEvent
version: 1.0
api-version: 1.17
author: NorthAlaska
main: me.NorthAlaska.BloodMoonEvent.Main
description: Each time night comes along there is a percent chance it will be a Blood Moon which will be rewarding but high risk

commands:
  summonBloodZombie: 
  bloodmoon:
    description: Starts or ends a Blood Moon
    usage: /<command> [start/end/reload]
    default: true
  giverandomloot: 